#!/usr/bin/env bash
set -euo pipefail

log_root="${1:-/tmp/dynasty-rebellion-tests}"
project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m0_tests.gd "$log_root/m0"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m1_combat_tests.gd "$log_root/m1"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m2_ui_tests.gd "$log_root/m2"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m3_content_tests.gd "$log_root/m3-content"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m3_runtime_tests.gd "$log_root/m3-runtime"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m3_enemy_tests.gd "$log_root/m3-enemy"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m3_boss_tests.gd "$log_root/m3-boss"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m3_balance_tests.gd "$log_root/m3-balance"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m4_map_tests.gd "$log_root/m4-map"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m4_expedition_tests.gd "$log_root/m4-expedition"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m4_objective_tests.gd "$log_root/m4-objective"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m4_settlement_tests.gd "$log_root/m4-settlement"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m5_campaign_tests.gd "$log_root/m5-campaign"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m5_army_tests.gd "$log_root/m5-army"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m5_research_tests.gd "$log_root/m5-research"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m5_general_tests.gd "$log_root/m5-general"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m5_faction_tests.gd "$log_root/m5-faction"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m5_persistence_tests.gd "$log_root/m5-persistence"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m6_flow_tests.gd "$log_root/m6-flow"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m6_ui_tests.gd "$log_root/m6-ui"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m6_experience_tests.gd "$log_root/m6-experience"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_m6_deck_editor_tests.gd "$log_root/m6-deck-editor"
"$project_root/scripts/ci/run_godot_test.sh" godot res://tests/run_art_presentation_tests.gd "$log_root/art-presentation"
